## We want to train a model clf then using clf try to predict unkmown data

In [56]:
import pandas as pd 
covid=pd.read_csv("z.Data/covid_data.csv")
covid.sample(frac=0.07, random_state=42)

,Date,Country,Total_Cases,New_Cases,Total_Deaths,New_Deaths,Recovered,Active_Cases,Serious_Critical,Tests_Per_Million,Population
13,2023-01-01,Iran,7500000,2800,144000,24,7100000,256000,650,88000,85000000
39,2023-01-01,UAE,1050000,400,2300,1,1035000,11700,32,385000,9770000
30,2023-01-01,Japan,33000000,12000,74000,85,32000000,926000,3200,95000,125800000
45,2023-01-01,Denmark,3200000,1100,6500,3,3150000,43500,42,285000,5830000

### Let we want to predicts New_Deaths after trainging model with other data

In [57]:
# Keep eveything without New_deaths bcz we want to predict it 
x= covid.drop("New_Deaths", axis=1) # axis=1 -> 
x.head()

,Date,Country,Total_Cases,New_Cases,Total_Deaths,Recovered,Active_Cases,Serious_Critical,Tests_Per_Million,Population
0,2023-01-01,USA,101000000,15000,1100000,95000000,4900000,8500,1850000,331000000
1,2023-01-01,India,45000000,8000,530000,44400000,670000,2200,350000,1380000000
2,2023-01-01,Brazil,37000000,7000,695000,35600000,705000,3100,160000,213000000
3,2023-01-01,France,38000000,12000,158000,37500000,342000,1800,210000,67400000
4,2023-01-01,Germany,36000000,11000,162000,35500000,338000,1700,195000,83200000

In [58]:
y=covid["New_Deaths"]
y.head()

0    120
1     50
2     45
3     85
4     78
Name: New_Deaths, dtype: int64

In [60]:
from sklearn.model_selection import train_test_split 
x = pd.get_dummies(x, drop_first=True)  # Object to Numaric
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)
x.head()

,Total_Cases,New_Cases,Total_Deaths,Recovered,Active_Cases,Serious_Critical,Tests_Per_Million,Population,Country_Australia,Country_Austria,...,Country_Spain,Country_Sweden,Country_Switzerland,Country_Thailand,Country_Turkey,Country_UAE,Country_UK,Country_USA,Country_Ukraine,Country_Vietnam
0,101000000,15000,1100000,95000000,4900000,8500,1850000,331000000,False,False,...,False,False,False,False,False,False,False,True,False,False
1,45000000,8000,530000,44400000,670000,2200,350000,1380000000,False,False,...,False,False,False,False,False,False,False,False,False,False
2,37000000,7000,695000,35600000,705000,3100,160000,213000000,False,False,...,False,False,False,False,False,False,False,False,False,False
3,38000000,12000,158000,37500000,342000,1800,210000,67400000,False,False,...,False,False,False,False,False,False,False,False,False,False
4,36000000,11000,162000,35500000,338000,1700,195000,83200000,False,False,...,False,False,False,False,False,False,False,False,False,False

In [61]:

from sklearn.ensemble import RandomForestRegressor 
model= RandomForestRegressor() 
model.fit(x_train, y_train) # For this X == this Y 
model.score(x_train, y_train)

0.9750142780282496

In [62]:
covid.dtypes

Date                 object
Country              object
Total_Cases           int64
New_Cases             int64
Total_Deaths          int64
New_Deaths            int64
Recovered             int64
Active_Cases          int64
Serious_Critical      int64
Tests_Per_Million     int64
Population            int64
dtype: object